/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_m_system;

import java.sql.*;
import javax.swing.*;
public class Admin extends javax.swing.JFrame {

    
     Connection con;
       PreparedStatement ps;
       ResultSet rs;
    public Admin() {
        initComponents();
        con=Library_M_System.connectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sortNames = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Bcode = new javax.swing.JTextField();
        Bprice = new javax.swing.JTextField();
        Bname = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Iscience = new javax.swing.JButton();
        Ihistrical = new javax.swing.JButton();
        iscientfic = new javax.swing.JButton();
        Iarts = new javax.swing.JButton();
        Icommerce = new javax.swing.JButton();
        Iothers = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Uscience = new javax.swing.JButton();
        Uscientfic = new javax.swing.JButton();
        Ucommerce = new javax.swing.JButton();
        Uhistrical = new javax.swing.JButton();
        Uothers = new javax.swing.JButton();
        Uarts = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Sscience = new javax.swing.JButton();
        Sscientfic = new javax.swing.JButton();
        Sarts = new javax.swing.JButton();
        Scommerce = new javax.swing.JButton();
        Sothers = new javax.swing.JButton();
        Shistrical = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Dscience = new javax.swing.JButton();
        Dcommerce = new javax.swing.JButton();
        Darts = new javax.swing.JButton();
        Dscientfic = new javax.swing.JButton();
        Dhistrical = new javax.swing.JButton();
        Dothers = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        Aothers = new javax.swing.JButton();
        Ahistrical = new javax.swing.JButton();
        Ascientfic = new javax.swing.JButton();
        Aarts = new javax.swing.JButton();
        Acommerce = new javax.swing.JButton();
        Ascience = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        sortNames.setText("Sort Book List ");
        sortNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortNamesActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\man-with-tie.png")); // NOI18N
        jLabel1.setText("   ADMIN");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2), "Update Data\n", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 24))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Book Code:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Book Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Price:");

        Bcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcodeActionPerformed(evt);
            }
        });

        Bprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpriceActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Insert", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        Iscience.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\external-browser.png")); // NOI18N
        Iscience.setText("     Science");
        Iscience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IscienceActionPerformed(evt);
            }
        });

        Ihistrical.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\external-browser.png")); // NOI18N
        Ihistrical.setText("    Histrical");
        Ihistrical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IhistricalActionPerformed(evt);
            }
        });

        iscientfic.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\external-browser.png")); // NOI18N
        iscientfic.setText("    Scientfic");
        iscientfic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iscientficActionPerformed(evt);
            }
        });

        Iarts.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\external-browser.png")); // NOI18N
        Iarts.setText("          Arts");
        Iarts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IartsActionPerformed(evt);
            }
        });

        Icommerce.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\external-browser.png")); // NOI18N
        Icommerce.setText("Commerce");
        Icommerce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IcommerceActionPerformed(evt);
            }
        });

        Iothers.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\external-browser.png")); // NOI18N
        Iothers.setText("     Others");
        Iothers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IothersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Icommerce, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Iarts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Iscience, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iscientfic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ihistrical, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Iothers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(Iscience)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Icommerce)
                .addGap(11, 11, 11)
                .addComponent(Iarts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iscientfic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ihistrical)
                .addGap(18, 18, 18)
                .addComponent(Iothers)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Update by Code", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        Uscience.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\web (1).png")); // NOI18N
        Uscience.setText("     Science");
        Uscience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UscienceActionPerformed(evt);
            }
        });

        Uscientfic.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\web (1).png")); // NOI18N
        Uscientfic.setText("     Scientfic");
        Uscientfic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UscientficActionPerformed(evt);
            }
        });

        Ucommerce.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\web (1).png")); // NOI18N
        Ucommerce.setText("Commerce");
        Ucommerce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UcommerceActionPerformed(evt);
            }
        });

        Uhistrical.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\web (1).png")); // NOI18N
        Uhistrical.setText("    Histrical");
        Uhistrical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UhistricalActionPerformed(evt);
            }
        });

        Uothers.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\web (1).png")); // NOI18N
        Uothers.setText("     Others");
        Uothers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UothersActionPerformed(evt);
            }
        });

        Uarts.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\web (1).png")); // NOI18N
        Uarts.setText("         Arts");
        Uarts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UartsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Uhistrical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Uscience, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ucommerce, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Uothers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Uarts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Uscientfic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(Uscience)
                .addGap(11, 11, 11)
                .addComponent(Ucommerce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Uarts)
                .addGap(15, 15, 15)
                .addComponent(Uscientfic)
                .addGap(18, 18, 18)
                .addComponent(Uhistrical)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Uothers)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Search by code", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        Sscience.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\research.png")); // NOI18N
        Sscience.setText("    Science");
        Sscience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SscienceActionPerformed(evt);
            }
        });

        Sscientfic.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\research.png")); // NOI18N
        Sscientfic.setText("   Scierntfic");
        Sscientfic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SscientficActionPerformed(evt);
            }
        });

        Sarts.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\research.png")); // NOI18N
        Sarts.setText("         Arts");
        Sarts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SartsActionPerformed(evt);
            }
        });

        Scommerce.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\research.png")); // NOI18N
        Scommerce.setText("Commerce");
        Scommerce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScommerceActionPerformed(evt);
            }
        });

        Sothers.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\research.png")); // NOI18N
        Sothers.setText("      Others");
        Sothers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SothersActionPerformed(evt);
            }
        });

        Shistrical.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\research.png")); // NOI18N
        Shistrical.setText("     Histrical");
        Shistrical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShistricalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sothers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sscientfic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sarts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Scommerce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sscience, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Shistrical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 33, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(Sscience)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Scommerce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sarts)
                .addGap(18, 18, 18)
                .addComponent(Sscientfic)
                .addGap(16, 16, 16)
                .addComponent(Shistrical)
                .addGap(16, 16, 16)
                .addComponent(Sothers)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Delete By code", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        Dscience.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\rubbish-bin.png")); // NOI18N
        Dscience.setText("     Science");
        Dscience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DscienceActionPerformed(evt);
            }
        });

        Dcommerce.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\rubbish-bin.png")); // NOI18N
        Dcommerce.setText(" Commerce");
        Dcommerce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DcommerceActionPerformed(evt);
            }
        });

        Darts.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\rubbish-bin.png")); // NOI18N
        Darts.setText("         Artcs");
        Darts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DartsActionPerformed(evt);
            }
        });

        Dscientfic.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\rubbish-bin.png")); // NOI18N
        Dscientfic.setText("    Scientfic");
        Dscientfic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DscientficActionPerformed(evt);
            }
        });

        Dhistrical.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\rubbish-bin.png")); // NOI18N
        Dhistrical.setText("     Histrical");
        Dhistrical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DhistricalActionPerformed(evt);
            }
        });

        Dothers.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\rubbish-bin.png")); // NOI18N
        Dothers.setText("      Others");
        Dothers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DothersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Dscience, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dothers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dhistrical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dscientfic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dcommerce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Darts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(Dscience)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Dcommerce)
                .addGap(18, 18, 18)
                .addComponent(Darts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Dscientfic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Dhistrical)
                .addGap(18, 18, 18)
                .addComponent(Dothers)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Show All data", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        Aothers.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\24-hours (1).png")); // NOI18N
        Aothers.setText("Others");
        Aothers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AothersActionPerformed(evt);
            }
        });

        Ahistrical.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\24-hours (1).png")); // NOI18N
        Ahistrical.setText("Histrical");
        Ahistrical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AhistricalActionPerformed(evt);
            }
        });

        Ascientfic.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\24-hours (1).png")); // NOI18N
        Ascientfic.setText("Scientfic");
        Ascientfic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AscientficActionPerformed(evt);
            }
        });

        Aarts.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\24-hours (1).png")); // NOI18N
        Aarts.setText("Arts");
        Aarts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AartsActionPerformed(evt);
            }
        });

        Acommerce.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\24-hours (1).png")); // NOI18N
        Acommerce.setText("Commerce");
        Acommerce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcommerceActionPerformed(evt);
            }
        });

        Ascience.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\24-hours (1).png")); // NOI18N
        Ascience.setText("Science");
        Ascience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AscienceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ascience)
                .addGap(32, 32, 32)
                .addComponent(Acommerce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(Aarts, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Ascientfic)
                .addGap(46, 46, 46)
                .addComponent(Ahistrical)
                .addGap(26, 26, 26)
                .addComponent(Aothers, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aothers)
                    .addComponent(Ahistrical)
                    .addComponent(Ascientfic)
                    .addComponent(Aarts)
                    .addComponent(Acommerce)
                    .addComponent(Ascience))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        Home.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\home-icon-silhouette.png")); // NOI18N
        Home.setText("Books House");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\play.png")); // NOI18N
        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\dcL\\Downloads\\exit (4).png")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bcode, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Bname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Bprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Home)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Bcode, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Bname, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(Bprice, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(57, 57, 57)
                        .addComponent(Home)
                        .addGap(30, 30, 30)
                        .addComponent(jButton7)
                        .addGap(131, 131, 131)))
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortNames, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(683, 683, 683))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(sortNames)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1368, 1368, 1368))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     jTextArea1.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    private void sortNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortNamesActionPerformed
        String names[]=jTextArea1.getText().split("\n");
        jTextArea1.setText("");
        for(int x=0; x<names.length; x++)
        {
            for(int y=0; y<names.length-1; y++)
            {
                if(names[y].compareTo(names[y+1])>0)
                {
                    String a =names[y];
                    names[y]=names[y+1];
                    names[y+1]=a;
                }
            }
        }
        for(int a=0; a<names.length; a++)
        {
            jTextArea1.append(names[a]+"\n");
        }
        
        
    }//GEN-LAST:event_sortNamesActionPerformed

    private void BpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BpriceActionPerformed

    private void BcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BcodeActionPerformed

    private void AcommerceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcommerceActionPerformed
         new CommerceData().setVisible(true);
    }//GEN-LAST:event_AcommerceActionPerformed

    private void IscienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IscienceActionPerformed
       String query="insert into science (code,name, price) value(?, ?, ?)";
       try{
           ps=con.prepareStatement(query);
           ps.setString(1, Bcode.getText());
           ps.setString(2, Bname.getText());
           ps.setString(3, Bprice.getText());
           ps.execute();
           JOptionPane.showMessageDialog(null, "okkk");
           Bcode.setText(null);
           Bname.setText(null);
           Bprice.setText(null);
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_IscienceActionPerformed

    private void IcommerceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IcommerceActionPerformed
        String query="insert into commerce (code,name, price) value(?, ?, ?)";
       try{
           ps=con.prepareStatement(query);
           ps.setString(1, Bcode.getText());
           ps.setString(2, Bname.getText());
           ps.setString(3, Bprice.getText());
           ps.execute();
           JOptionPane.showMessageDialog(null, "okkk");
           Bcode.setText(null);
           Bname.setText(null);
           Bprice.setText(null);
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_IcommerceActionPerformed

    private void IartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IartsActionPerformed
         String query="insert into arts (code,name, price) value(?, ?, ?)";
       try{
           ps=con.prepareStatement(query);
           ps.setString(1, Bcode.getText());
           ps.setString(2, Bname.getText());
           ps.setString(3, Bprice.getText());
           ps.execute();
           JOptionPane.showMessageDialog(null, "okkk");
           Bcode.setText(null);
           Bname.setText(null);
           Bprice.setText(null);
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_IartsActionPerformed

    private void iscientficActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iscientficActionPerformed
         String query="insert into scientfic (code,name, price) value(?, ?, ?)";
       try{
           ps=con.prepareStatement(query);
           ps.setString(1, Bcode.getText());
           ps.setString(2, Bname.getText());
           ps.setString(3, Bprice.getText());
           ps.execute();
           JOptionPane.showMessageDialog(null, "okkk");
           Bcode.setText(null);
           Bname.setText(null);
           Bprice.setText(null);
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_iscientficActionPerformed

    private void IhistricalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IhistricalActionPerformed
       String query="insert into histical (code,name, price) value(?, ?, ?)";
       try{
           ps=con.prepareStatement(query);
           ps.setString(1, Bcode.getText());
           ps.setString(2, Bname.getText());
           ps.setString(3, Bprice.getText());
           ps.execute();
           JOptionPane.showMessageDialog(null, "okkk");
           Bcode.setText(null);
           Bname.setText(null);
           Bprice.setText(null);
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_IhistricalActionPerformed

    private void IothersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IothersActionPerformed
 String query="insert into others (code,name, price) value(?, ?, ?)";
       try{
           ps=con.prepareStatement(query);
           ps.setString(1, Bcode.getText());
           ps.setString(2, Bname.getText());
           ps.setString(3, Bprice.getText());
           ps.execute();
           JOptionPane.showMessageDialog(null, "okkk");
           Bcode.setText(null);
           Bname.setText(null);
           Bprice.setText(null);
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_IothersActionPerformed

    private void UscienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UscienceActionPerformed
        String query ="update science SET name=?, price=? where code=?";
        try{
           ps=con.prepareStatement(query);
           ps.setString(3, Bcode.getText());
           ps.setString(1, Bname.getText());
           ps.setString(2, Bprice.getText());
           ps.execute();
           JOptionPane.showMessageDialog(null, "okkk");
           
           ps.close();
           Bcode.setText(null);
           Bname.setText(null);
           Bprice.setText(null);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_UscienceActionPerformed

    private void UcommerceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UcommerceActionPerformed
         String query ="update commerce SET name=?, price=? where code=?";
        try{
           ps=con.prepareStatement(query);
           ps.setString(3, Bcode.getText());
           ps.setString(1, Bname.getText());
           ps.setString(2, Bprice.getText());
           ps.execute();
           JOptionPane.showMessageDialog(null, "okkk");
           ps.close();
           Bcode.setText(null);
           Bname.setText(null);
           Bprice.setText(null);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_UcommerceActionPerformed

    private void UartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UartsActionPerformed
         String query ="update arts SET name=?, price=? where code=?";
        try{
           ps=con.prepareStatement(query);
           ps.setString(3, Bcode.getText());
           ps.setString(1, Bname.getText());
           ps.setString(2, Bprice.getText());
           ps.execute();
           JOptionPane.showMessageDialog(null, "okkk");
           ps.close();
           Bcode.setText(null);
           Bname.setText(null);
           Bprice.setText(null);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_UartsActionPerformed

    private void UhistricalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UhistricalActionPerformed
        String query ="update histical SET name=?, price=? where code=?";
        try{
           ps=con.prepareStatement(query);
           ps.setString(3, Bcode.getText());
           ps.setString(1, Bname.getText());
           ps.setString(2, Bprice.getText());
           ps.execute();
           JOptionPane.showMessageDialog(null, "okkk");
           ps.close();
           Bcode.setText(null);
           Bname.setText(null);
           Bprice.setText(null);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_UhistricalActionPerformed

    private void UothersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UothersActionPerformed
         String query ="update others SET name=?, price=? where code=?";
        try{
           ps=con.prepareStatement(query);
           ps.setString(3, Bcode.getText());
           ps.setString(1, Bname.getText());
           ps.setString(2, Bprice.getText());
           ps.execute();
           JOptionPane.showMessageDialog(null, "okkk");
           ps.close();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_UothersActionPerformed

    private void SscienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SscienceActionPerformed
        String query="select * from science where code= ?";
        try
        {
            ps=con.prepareStatement(query);
            ps.setString(1, Bcode.getText());
            rs=ps.executeQuery();
            if(rs.next())
            {
                String add=rs.getString("name");
                Bname.setText(add);
                String add1 = rs.getString("price");
                Bprice.setText(add1);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
                
                
                
    }//GEN-LAST:event_SscienceActionPerformed

    private void ScommerceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScommerceActionPerformed
        String query="select * from commerce where code= ?";
        try
        {
            ps=con.prepareStatement(query);
            ps.setString(1, Bcode.getText());
            rs=ps.executeQuery();
            if(rs.next())
            {
                String add=rs.getString("name");
                Bname.setText(add);
                String add1 = rs.getString("price");
                Bprice.setText(add1);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ScommerceActionPerformed

    private void SartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SartsActionPerformed
       String query="select * from arts where code= ?";
        try
        {
            ps=con.prepareStatement(query);
            ps.setString(1, Bcode.getText());
            rs=ps.executeQuery();
            if(rs.next())
            {
                String add=rs.getString("name");
                Bname.setText(add);
                String add1 = rs.getString("price");
                Bprice.setText(add1);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SartsActionPerformed

    private void SscientficActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SscientficActionPerformed
        String query="select * from scientfic where code= ?";
        try
        {
            ps=con.prepareStatement(query);
            ps.setString(1, Bcode.getText());
            rs=ps.executeQuery();
            if(rs.next())
            {
                String add=rs.getString("name");
                Bname.setText(add);
                String add1 = rs.getString("price");
                Bprice.setText(add1);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SscientficActionPerformed

    private void ShistricalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShistricalActionPerformed
       String query="select * from histical where code= ?";
        try
        {
            ps=con.prepareStatement(query);
            ps.setString(1, Bcode.getText());
            rs=ps.executeQuery();
            if(rs.next())
            {
                String add=rs.getString("name");
                Bname.setText(add);
                String add1 = rs.getString("price");
                Bprice.setText(add1);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ShistricalActionPerformed

    private void SothersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SothersActionPerformed
        String query="select * from others where code= ?";
        try
        {
            ps=con.prepareStatement(query);
            ps.setString(1, Bcode.getText());
            rs=ps.executeQuery();
            if(rs.next())
            {
                String add=rs.getString("name");
                Bname.setText(add);
                String add1 = rs.getString("price");
                Bprice.setText(add1);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SothersActionPerformed

    private void DscienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DscienceActionPerformed
        String query="delete from science where code =?";
        try{
            ps=con.prepareStatement(query);
            ps.setString(1, Bcode.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null, "Delete Confirmed");
            Bcode.setText(null);
            Bname.setText(null);
            Bprice.setText(null);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
            
        
    }//GEN-LAST:event_DscienceActionPerformed

    private void DcommerceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DcommerceActionPerformed
        String query="delete from commerce where code =?";
        try{
            ps=con.prepareStatement(query);
            ps.setString(1, Bcode.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null, "Delete Confirmed");
            Bcode.setText(null);
            Bname.setText(null);
            Bprice.setText(null);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DcommerceActionPerformed

    private void DartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DartsActionPerformed
         String query="delete from arts where code =?";
        try{
            ps=con.prepareStatement(query);
            ps.setString(1, Bcode.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null, "Delete Confirmed");
            Bcode.setText(null);
            Bname.setText(null);
            Bprice.setText(null);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DartsActionPerformed

    private void DscientficActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DscientficActionPerformed
        String query="delete from scientfic where code =?";
        try{
            ps=con.prepareStatement(query);
            ps.setString(1, Bcode.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null, "Delete Confirmed");
            Bcode.setText(null);
            Bname.setText(null);
            Bprice.setText(null);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DscientficActionPerformed

    private void DhistricalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DhistricalActionPerformed
         String query="delete from histical where code =?";
        try{
            ps=con.prepareStatement(query);
            ps.setString(1, Bcode.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null, "Delete Confirmed");
            Bcode.setText(null);
            Bname.setText(null);
            Bprice.setText(null);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DhistricalActionPerformed

    private void DothersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DothersActionPerformed
         String query="delete from others where code =?";
        try{
            ps=con.prepareStatement(query);
            ps.setString(1, Bcode.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null, "Delete Confirmed");
            Bcode.setText(null);
            Bname.setText(null);
            Bprice.setText(null);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DothersActionPerformed

    private void AscienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AscienceActionPerformed
        new scienceDatainfo().setVisible(true);
    }//GEN-LAST:event_AscienceActionPerformed

    private void AartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AartsActionPerformed
      new ArtsData().setVisible(true);
    }//GEN-LAST:event_AartsActionPerformed

    private void AhistricalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AhistricalActionPerformed
       new HistroyData().setVisible(true);
    }//GEN-LAST:event_AhistricalActionPerformed

    private void AothersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AothersActionPerformed
       new Others().setVisible(true);
    }//GEN-LAST:event_AothersActionPerformed

    private void AscientficActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AscientficActionPerformed
         new ScientficData().setVisible(true);
    }//GEN-LAST:event_AscientficActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
         new Book_House().setVisible(true);
         dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Weclome().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void UscientficActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UscientficActionPerformed
         String query ="update scientfic SET name=?, price=? where code=?";
         try{
             ps=con.prepareStatement(query);
           ps.setString(3, Bcode.getText());
           ps.setString(1, Bname.getText());
           ps.setString(2, Bprice.getText());
           ps.execute();
           JOptionPane.showMessageDialog(null, "okkk");
           ps.close();
           Bcode.setText(null);
           Bname.setText(null);
           Bprice.setText(null);
           
         }catch(Exception e)
         {
              JOptionPane.showMessageDialog(null, e);
         }
    }//GEN-LAST:event_UscientficActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aarts;
    private javax.swing.JButton Acommerce;
    private javax.swing.JButton Ahistrical;
    private javax.swing.JButton Aothers;
    private javax.swing.JButton Ascience;
    private javax.swing.JButton Ascientfic;
    private javax.swing.JTextField Bcode;
    private javax.swing.JTextField Bname;
    private javax.swing.JTextField Bprice;
    private javax.swing.JButton Darts;
    private javax.swing.JButton Dcommerce;
    private javax.swing.JButton Dhistrical;
    private javax.swing.JButton Dothers;
    private javax.swing.JButton Dscience;
    private javax.swing.JButton Dscientfic;
    private javax.swing.JButton Home;
    private javax.swing.JButton Iarts;
    private javax.swing.JButton Icommerce;
    private javax.swing.JButton Ihistrical;
    private javax.swing.JButton Iothers;
    private javax.swing.JButton Iscience;
    private javax.swing.JButton Sarts;
    private javax.swing.JButton Scommerce;
    private javax.swing.JButton Shistrical;
    private javax.swing.JButton Sothers;
    private javax.swing.JButton Sscience;
    private javax.swing.JButton Sscientfic;
    private javax.swing.JButton Uarts;
    private javax.swing.JButton Ucommerce;
    private javax.swing.JButton Uhistrical;
    private javax.swing.JButton Uothers;
    private javax.swing.JButton Uscience;
    private javax.swing.JButton Uscientfic;
    private javax.swing.JButton iscientfic;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton sortNames;
    // End of variables declaration//GEN-END:variables
}
